version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install
          command: uname -a
      - run:
          name: build
          command: build/aws/amazon_ubuntu_build.sh