version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: update
          command: 'sudo apt-get update'
      - run:
          name: install
          command: 'sudo apt-get install git ksh'    # 'apt-get update' first, or else you will get: "E: Unable to locate package ksh"
      - run:
          name: build
          command: build/aws/amazon_ubuntu_build.sh